version: '3'

services:
  database:
    image: postgres:13
    ports:
      - "5532:5432"
    environment:
      POSTGRES_DB: project
      POSTGRES_PASSWORD: password
      POSTGRES_USER: developer
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
